export const cadastroStrings = {
  addButton: {
    label: "Adicionar familiar",
    ariaLabel: "Adicionar novo familiar pediátrico",
  },
  modal: {
    title: "Cadastro pediátrico",
    description: "Preencha os dados essenciais para o cuidado integrado da criança.",
    closeLabel: "Fechar cadastro",
    cancel: "Cancelar",
    back: "Voltar",
    next: "Próximo",
    save: "Salvar cadastro",
  },
  steps: {
    personal: {
      id: "personal",
      title: "Dados pessoais",
      description: "Identificação, contato e avatar",
    },
    medical: {
      id: "medical",
      title: "Dados clínicos",
      description: "Histórico de saúde e medições",
    },
    contacts: {
      id: "contacts",
      title: "Responsáveis",
      description: "Contatos principais e emergência",
    },
    insurance: {
      id: "insurance",
      title: "Convênio",
      description: "Planos e documentos",
    },
    routine: {
      id: "routine",
      title: "Rotina",
      description: "Escola, terapias e hábitos",
    },
    attachments: {
      id: "attachments",
      title: "Anexos",
      description: "Documentos e observações",
    },
  },
  personal: {
    avatarLabel: "Avatar",
    avatarHint: "Foto quadrada até 2 MB. Você pode arrastar, cortar e ajustar o zoom.",
    cropTitle: "Ajustar avatar",
    cropDescription: "Use o zoom e arraste para centralizar o rosto.",
    cropConfirm: "Aplicar recorte",
    cropCancel: "Cancelar",
    cropZoomLabel: "Zoom",
    removeAvatar: "Remover avatar",
    uploadCta: "Enviar avatar",
    cropCta: "Ajustar recorte",
    nameLabel: "Nome completo",
    namePlaceholder: "Nome e sobrenome",
    nicknameLabel: "Apelido (opcional)",
    birthDateLabel: "Data de nascimento",
    sexoLabel: "Sexo",
    pronomeLabel: "Pronome",
    corLabel: "Cor/raça",
    bloodTypeLabel: "Tipo sanguíneo",
    naturalidadeCidade: "Cidade de nascimento",
    naturalidadeUf: "UF",
    addressTitle: "Endereço",
    addressStreet: "Logradouro",
    addressNumber: "Número",
    addressDistrict: "Bairro",
    addressCity: "Cidade",
    addressState: "UF",
    addressZip: "CEP",
    contactsTitle: "Contatos",
    contactMain: "Telefone principal",
    contactExtra: "Telefone extra",
    contactEmail: "E-mail",
    idadeResumo: (idade: string) => `Idade: ${idade}`,
  },
  medical: {
    alergiasTitle: "Alergias",
    addAlergia: "Adicionar alergia",
    condicoesTitle: "Condições clínicas",
    medicacoesTitle: "Medicações atuais",
    addMedicacao: "Adicionar medicação",
    cirurgiasTitle: "Cirurgias e internações",
    addCirurgia: "Adicionar evento",
    vacinasTitle: "Vacinas",
    addVacina: "Adicionar vacina",
    crescimentoTitle: "Crescimento",
    addMedida: "Registrar medida",
    pediatraTitle: "Pediatra de referência",
    preferenciasTitle: "Preferências de cuidado",
    imcResumo: (imc: string) => `IMC: ${imc}`,
  },
  contacts: {
    responsaveisTitle: "Responsáveis",
    addResponsavel: "Adicionar responsável",
    emergenciaTitle: "Contato de emergência",
    addEmergencia: "Adicionar contato",
    autorizadosTitle: "Autorizados para retirada",
    addAutorizado: "Adicionar autorizado",
  },
  insurance: {
    hasInsuranceLabel: "Possui convênio",
    providerLabel: "Operadora",
    cardNumberLabel: "Número da carteirinha",
    validadeLabel: "Validade",
    planLabel: "Plano",
    cardUploadTitle: "Carteirinha",
    docUploadTitle: "Documentos da criança",
    uploadHint: "Arquivos JPG, PNG ou PDF com até 5 MB.",
  },
  routine: {
    schoolTitle: "Escola",
    routineSleepTitle: "Rotina de sono",
    routineFoodTitle: "Alimentação",
    therapiesTitle: "Terapias",
    addTherapy: "Adicionar terapia",
    activitiesTitle: "Atividades",
    addActivity: "Adicionar atividade",
  },
  attachments: {
    uploadTitle: "Anexos",
    uploadHint: "Arraste ou selecione arquivos (jpg, png, pdf) até 10 MB",
    notesLabel: "Observações gerais",
    consentLabel: "Autorizo o tratamento dos dados para fins de cuidado e atendimento.",
  },
  messages: {
    created: "Familiar cadastrado com sucesso.",
    createError: "Não foi possível cadastrar o familiar. Tente novamente.",
    uploadError: "Falha ao enviar arquivo. Verifique o formato e o tamanho.",
  },
};
